language: generic
cache:
  directories:
    - all_teh_gems
install:
  - git clone https://github.com/Charcoal-SE/metasmoke.git
  - ln -s $(pwd)/all_teh_gems $(pwd)/metasmoke/vendor/bundle
  - cd metasmoke
  - bundle check --path=vendor/bundle || bundle install --path=vendor/bundle --jobs=4 --retry=3 
  - echo $key | base64 --decode > sshkey.pem
  - bundle exec cap travis_production deploy
