language: generic
after_script:
  - git clone https://github.com/Charcoal-SE/metasmoke.git
  - cd metasmoke
  - ls
  - bundle check --path=vendor/bundle || bundle install --path=vendor/bundle --jobs=4 --retry=3 
